flowchart TD
    A[Contactos Geológicos] --> B[Contactos Mecánicos]
    A --> C[Contactos Sedimentarios]
    A --> D[Contactos Ígneos]
    
    B --> B1[Fallas]
    B --> B2[Cabalgamientos]
    
    C --> C1[Concordantes]
    C --> C2[Discordantes o Discordancias]
    
    D --> D1[Intrusivos]
    D --> D2[Efusivos/Lavicos]
    
    style A fill:#4b6584,stroke:#333,stroke-width:2px,color:#fff
    style B fill:#fc5c65,stroke:#333,stroke-width:1px,color:#fff
    style C fill:#26de81,stroke:#333,stroke-width:1px,color:#fff
    style D fill:#fd9644,stroke:#333,stroke-width:1px,color:#fff
